name: "mouth"
features:
  - path: "1.png"
    x: 1100
    y: 500
  - path: "2.png"
    x: 1150
    y: 600
  - path: "3.png"
    x: 1100
    y: 600
  - path: "4.png"
    x: 1000
    y: 600
  - path: "5.png"
    x: 1050
    y: 650
  - path: "6.png"
    x: 950
    y: 600
  - path: "7.png"
    x: 1000
    y: 650
  - path: "8.png"
    x: 975
    y: 650
