name: "eyes"
features:
  - path: "1.png"
    x: 950
    y: 250
    x2: 1350
    y2: 250
  - path: "2.png"
    x: 950
    y: 250
    x2: 1350
    y2: 250
  - path: "3.png"
    x: 950
    y: 250
    x2: 1350
    y2: 250
  - path: "4.png"
    x: 950
    y: 250
    x2: 1350
    y2: 250
  - path: "5.png"
    x: 950
    y: 250
    x2: 1350
    y2: 250
  - path: "6.png"
    x2: 950
    y2: 250
    x: 1350
    y: 250
  - path: "7.png"
    x: 950
    y: 250
    x2: 1350
    y2: 250
  - path: "8.png"
    mirror: false
    x: 950
    y: 250
    x2: 1350
    y2: 250
  - path: "9.png"
    x: 1000
    y: 250
    x2: 1350
    y2: 250
  - path: "10.png"
    x: 900
    y: 225
    x2: 1300
    y2: 225
  - path: "9.png"
    x2: 1000
    y2: 250
    x: 1350
    y: 250
